### ISSUE TITLE
Checks against strings don't work properly

### ISSUE THREAD

**Issue by itay** [kapouille/mongoquery#3]
See the following case:

```
>>> import mongoquery
>>> a = {"a": "5", "b": 6}
>>> query = mongoquery.Query({"a": 2})
>>> query.match(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/mongoquery/__init__.py", line 23, in match
    return self._match(self._definition, entry)
  File "/usr/local/lib/python2.7/site-packages/mongoquery/__init__.py", line 29, in _match
    for sub_operator, sub_condition in condition.items()
  File "/usr/local/lib/python2.7/site-packages/mongoquery/__init__.py", line 29, in <genexpr>
    for sub_operator, sub_condition in condition.items()
  File "/usr/local/lib/python2.7/site-packages/mongoquery/__init__.py", line 72, in _process_condition
    return self._match(condition, extracted_data)
  File "/usr/local/lib/python2.7/site-packages/mongoquery/__init__.py", line 33, in _match
    return condition in entry
TypeError: 'in <string>' requires string as left operand, not int
```

This happens because we have:

```
    def _match(self, condition, entry):
        if isinstance(condition, Mapping):
            return all(
                self._process_condition(sub_operator, sub_condition, entry)
                for sub_operator, sub_condition in condition.items()
            )
        else:
            if isinstance(entry, Sequence): <----- HERE
                return condition in entry
            else:
                return condition == entry
```

`str` is actually a subtype of `collections.Sequence`, and thus we try and do an "in" comparison, when we really want equality. This seems like a bug even if you had two strings, because this can happen:

```
>>> b = {"a": "567", "b": 6}
>>> query2 = mongoquery.Query({"a": "6"})
>>> query2.match(b)
True
```

Same reason - we're doing an `in` when you want to do a strict equality check. There are a couple of possible fixes:
1. Check against explicit types instead of `Sequence`
2. Ensure that it is not a string-like type (e.g. bytes, unicode, str, etc)

**Comment by foolswood** [comment]
Good find, my personal preference is for option 2, grab a basestring and check that first.
